repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: trailing-whitespace
    exclude: ^(test/example_results)
  - id: end-of-file-fixer
    exclude: ^(test/example_results/cheetah)
  - id: check-yaml
  - id: check-added-large-files
- repo: https://github.com/pseewald/fprettify
  rev: v0.3.7
  hooks:
  - id: fprettify
