# To use:
#
#   $ mamba env create -f environment.yml
#   $ mamba activate rgpotpy
#
name: gaussjacquad
channels:
  - conda-forge
dependencies:
  - compilers
  - meson
  - gfortran
  - pkg-config
  - openblas
  - fpm
  - fprettify
  # Python, Sympy
  - ipython
  - sympy
  - numpy
  - jupytext
  - papermill
  - ipykernel
  # More testing
  - pytest
  # Headers
  - jinja2
  # Documentation
  - pandoc
  - doxygen==1.9.1 # for doxyYoda
  - graphviz # for dot
  # Release management
  - towncrier
  - tbump
