name = "GaussJacobiQuad"
version = "0.1.0"
license = "MIT"
author = "Rohit Goswami"
maintainer = "rog32@hi.is"
copyright = "Copyright 2023--present, featom developers"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false
[install]
library = false
[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"

